---

# Type the following characters with a particular key combination.
# Useful for non-english keyboard layouts where the typing automation
# produces incorrect results.
# special_chars:
#   - character: /
#     key: 7
#     command: shift
#   - character: "#"
#     key: 3
#     command: gralt