---
special_chars:
  - character: "~"
    key_sym: 0xfe53
    space_after: true
  - character: "^"
    key_sym: 0xfe52
    space_after: true
  - character: "`"
    key_sym: 0xfe50
    space_after: true
