---

# Override the way these characters are typed ON LINUX ONLY.
# Useful for non-english keyboard layouts where the typing automation somtimes
# produces incorrect results on Linux.
special_chars:
  - character: "~"
    # Can be looked up with xmodmap -pk
    key_sym: 0xfe53
    # Needed to type "dead" keys by themselves, because they also modify a previous letter (e.g. accents)
    space_after: true

# Duration until an unlocked secret snippet is locked again.
# Duration is in Golang format: https://golang.org/pkg/time/#ParseDuration
secret_ttl: 10m

# Hotkey combination to activate and show the snippet window.
activate_hotkeys: [q, alt]

# Hotkey combination to show snippets.yml in the editor.
editor_hotkeys: [e, alt]

# Command with which to open snippets.yml when Alt + e is pressed. Empty by default.
editor_cmd: vim
