---

# Make snippet type the following characters with a particular key combination ON LINUX ONLY.
# Useful for non-english keyboard layouts where the typing automation somtimes
# produces incorrect results on Linux.
# Possible key and command values: see https://github.com/go-vgo/robotgo/blob/master/docs/keys.md
# Additionally, snippet supports "gralt" command.
special_chars:
  - character: /
    key: 7
    command: shift
  - character: "#"
    key: 3
    command: gralt

# Duration until an unlocked secret snippet is locked again.
# Duration is in Golang format: https://golang.org/pkg/time/#ParseDuration
secret_ttl: 10m

# Hotkey combination to activate and show the snippet window.
activate_hotkeys: [q, alt]

# Hotkey combination to show snippets.yml in the editor.
editor_hotkeys: [e, alt]

# Command with which to open snippets.yml when Alt + e is pressed. Empty by default.
editor_cmd: vim
