name: CI

on:
  push:
    branches: ["**"]
    tags-ignore: ["v*"]
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install additional build tools
      run: |
        go get golang.org/x/lint/golint
        make install-sys-packages

    - name: Test
      run: make test

    - name: Lint
      run: make lint

    - name: Build Linux
      run: make build-linux
